--- 
abstract: Output FOAF files from Gedcom individuals and families
author: Brian Cassidy <bricas@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Gedcom-FOAF
no_index: 
  directory: 
    - inc
    - t
requires: 
  Gedcom: 0
  Test::More: 0
  XML::LibXML: 0
version: 0.03
